`define CSR_READ_ONLY 2'b00
`define CSR_WRITE 2'b01
`define CSR_SET 2'b10
`define CSR_CLEAR 2'b11

`define INSTRUCTION_ADDRESS_MISALIGNED_CODE 0
`define ILLEGAL_INSTRUCTION_CODE 2
`define BREAKPOINT_CODE 3
`define LOAD_ADDRESS_MISALIGNED_CODE 4
`define STORE_ADDRESS_MISALIGNED_CODE 6
`define ECALL_CODE 11
