name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/toshipp/rv/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      env:
        OBJCOPY: riscv64-elf-objcopy
        RISCV_PREFIX: riscv64-elf-
    steps:
      - uses: actions/checkout@v2
      - run: make test
