name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.hub.docker.com/library/archlinux
      env:
        RISCV_PREFIX: riscv64-elf-
    steps:
      - uses: actions/checkout@v2
      - run: |
          pacman -Sy
          pacman -S --noconfirm --needed \
          base-devel \
          git \
          iverilog \
          verilator \
          riscv64-elf-gcc \
          riscv64-elf-newlib \
          yosys
      - run: make test
